### ISSUE TITLE
Replace remote font with local ones. 

### ISSUE THREAD

**Issue by ducdetronquito** [ResponSySS/responsyss.github.io#1]
The page take more than 5s to load because of the load of `youngserif` and `kaushan-script` stylesheets :/

Would it be possible to use a single local font ? (Maybe Fira is avaible on every browser ?)

**#unowadamsayinbru**

**Comment by sylsau** [comment]
First off, thank you my fellow programmer of the interwebs.
I'M ON IT BROTHA OF THE MEMES!

**Comment by ducdetronquito** [comment]
I see some work around:
1. Upload the fonts on github
2. Use ["safe" web fonts](https://www.w3schools.com/cssref/css_websafe_fonts.asp)
3. Reduce the number of fonts

**Comment by sylsau** [comment]
1. Thanks I'M NOT A FUCKING IDIOT
2. I ALREADY SET SOME SAFE FONTS IN CASE THE PROPER FONTS DON'T LOAD
3. True though ;_;

**Comment by ducdetronquito** [comment]
![](https://m.popkey.co/d600ae/kN8E_f-maxage-0_s-200x150.gif)

**Comment by sylsau** [comment]
Bon j'ai pas compris pourquoi Kaushan Script marchait plus quand je l'ai mis en local, du coup j'ai pris les CSS de Google et je pense qu'on peut safely assume que les serveurs Google sont plus rapides que ceux de GH :3 
J'ai enlevé une police inutile aussi.

**Comment by ducdetronquito** [comment]
Bizarre :/

Garde quand même cette "issue" ouverte: si on pouvait, à terme, éviter de taper sur les serveurs de Google ça pourrait être pas mal :) (sans vouloir faire mon privacy nazi :p)

**Comment by ducdetronquito** [comment]
Je viens de refaire un test au boulot comme l'ordi et la connection sont plus lents que chez moi, et voilà ce que ça donne au chargement de la page principale. C'est facile 20-30% plus rapide qu'hier :)
![loading_time_main_page_aufhebung](https://user-images.githubusercontent.com/9960268/28560735-23b6290e-711c-11e7-8536-f9974ecf2bf7.png)

Faudrait voir si, dans un premier temps, on peut pas virer les fichiers liés à font-awesmone.

**Comment by sylsau** [comment]
Je t'avoue que j'ai pas touché aux autres CSS que `main`, pas trop eu le temps. De ce que j'ai compris en 3 min ça s'inclut dans toutes les pages HTML avec `<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css" />` mais aucune mention dans les fichiers CSS.

**Comment by ducdetronquito** [comment]
Je viens de virer la dépendance à font-awesome :)
