### ISSUE TITLE
Enlever l'icone centrale ?

### ISSUE THREAD

**Issue by ducdetronquito** [ResponSySS/responsyss.github.io#11]
Yo !

Il me semble que l'on pourrait enlever l'icone "A": je trouve qu'il casse un peu le design global du site.

Qu'est ce que tu en penses ? :)

**Comment by sylsau** [comment]
Tiens bah j'avais pas vu cette issue mais je viens de le faire \o/
#lesGrandsEspritsSeRejoignent

**Comment by ducdetronquito** [comment]
Bien joué, c'est nickel :ok_hand: ! :)
