### ISSUE TITLE
Social media icons fucked up m8

### ISSUE THREAD

**Issue by sylsau** [ResponSySS/responsyss.github.io#12]
Les résals sociaux.
![resalsociaux](https://user-images.githubusercontent.com/3996262/28637359-91cb8382-7241-11e7-9420-e26abcf101e0.png)

Voir au pied de: https://responsyss.github.io/2015-01-dear-diary/

**Comment by ducdetronquito** [comment]
Je pense que j'ai du virer une librairie qui était nécessaire pour les afficher... :1st_place_medal: 

On pourrait les remplacer par des icones optionelles, comme tu peux en trouver aux bas des articles de framasoft ([exemple](https://framablog.org/2017/07/24/goat-in-the-shell-debunke-le-deep-web/)).

C'est pas mal niveau vie privée :)

Qu'est ce que tu en penses ?

**Comment by sylsau** [comment]
OSEF de LinkedIn d'ailleurs lel.
J'aurais tendance à dire non, il faut rendre le truc simple. Si le fait qu'il y ait un lien soit dérangeant, on peut faire un mini-truc JS qui colle des morceaux de mots pour l'écrire, genre `<script type="text/javascript">document.write("<a href=\"ma"+"il"+"to:"+new Array("mail","systemic"+"response.com").join("@")+"\">"+new Array("mail","systemic"+"response.com").join( "@")+"</"+"a>");</script></p>` (c'est le code dont je me sers pour écrire mon adresse  mail sur mon site).

**Comment by ducdetronquito** [comment]
C'est pas pour le fait d'avoir un lien, mais plutot le fait d'utiliser les images d'icones qui sont stockées chez facebook/twitter/etc.

Mais du coup, pour rester sur un truc simple, on peut héberger nous même les icônes ?

**Comment by sylsau** [comment]
Oui voilà.
