### ISSUE TITLE
Idées d'articles

### ISSUE THREAD

**Issue by sylsau** [ResponSySS/responsyss.github.io#14]
Voir wiki :3

**Comment by ducdetronquito** [comment]
Bonne idée le petit wiki :)

Je serais bien tenté, à moyen terme, de faire une introduction (une relecture/étude du texte assez accessible) au chapitre 1er du capital sous forme de podcasts audio.

Pour l'instant c'est une idée, et faut d'abord que je finisse de prendre mes notes (et que la SNCF me retrouve ma liseuse que j'ai oublié dans le train) pour commencer réellement à écrire quelque chose. (Et en dernier lieu, trouver un bon micro)

Quéstenpenses ?
