### ISSUE TITLE
Impression défectueuse sur FF

### ISSUE THREAD

**Issue by sylsau** [ResponSySS/responsyss.github.io#16]
Résultat (PDF de 1 seule page) :  ![pdf_de_1_p](https://user-images.githubusercontent.com/3996262/31583231-385caf3e-b197-11e7-8acc-918ed7a40a2e.png)

Mode Reader View:
* on voit pas les < span > :  ![screenshot_2017-10-15_11-02-31](https://user-images.githubusercontent.com/3996262/31583246-a521b1fa-b197-11e7-8ee5-7cd45371c0ba.jpg)

**Comment by ducdetronquito** [comment]
En fouillant sur l'internet mondial, il semblerait que les problèmes d'impressions soit un bug récurrent de Firefox, donc on ne risque pas de pouvoir y faire grand chose :/

Pour ce qui est des spans, il semblerait que tout s'affiche correctement sur le reader view de firefox maintenant que les notes de bas de pages n'ont plus de `<span>`.

**Comment by sylsau** [comment]
En fait c'est lié au CSS, au mode de `display` `flex` qui ne permet pas d'imprimer des pages complètes. Tandis que `display: block` le permet.

**Comment by sylsau** [comment]
Oui pour les spans c'est ok

**Comment by ducdetronquito** [comment]
![Ah!](https://yt3.ggpht.com/-PNa9vAt11aY/AAAAAAAAAAI/AAAAAAAAAAA/9SkJd8YnYKg/s48-c-k-no-mo-rj-c0xffffff/photo.jpg)
Bah si je vire le mode flex, on a plus d'interface :P

**Comment by sylsau** [comment]
Oui oui je sais c'est pour ça que j'ai laissé l'issue fermé puis bon si les gens veulent l'imprimer ils prennent le PDF
