### ISSUE TITLE
Gestion des "subtitle" dans les posts :-3

### ISSUE THREAD

**Issue by sylsau** [ResponSySS/responsyss.github.io#17]
Histoire que ça donne ça: 
![screenshot_2017-10-16_19-50-27](https://user-images.githubusercontent.com/3996262/31626523-563d3280-b2aa-11e7-968e-7f864cbe7a64.png)

![lel](https://pbs.twimg.com/media/DMOFMNsW0AAnKLV.jpg)

**Comment by ducdetronquito** [comment]
Du coup c'est fait ça, non ? :)

**Comment by sylsau** [comment]
Oui
