### ISSUE TITLE
Corriger le texte DLMEME

### ISSUE THREAD

**Issue by sylsau** [ResponSySS/responsyss.github.io#18]
"De la misère en milieu étudiant" pour les intimes ;-p :-o 

Bon j'ai plus le repo sur mon ordi donc je peux pas `jekyll-build` le site du coup bah faudra corriger DLMEME car ça doit pas être bon niveau formattage.

**Comment by ducdetronquito** [comment]
Qu'est ce qui ne va pas sur le formatage de ce texte ?

**Comment by sylsau** [comment]
Non c'est bon
