### ISSUE TITLE
jekyll warning: unresolved specs

### ISSUE THREAD

**Issue by sylsau** [ResponSySS/responsyss.github.io#21]
Bon j'ai essayé de refaire `jekyll build -I` après avoir supprimer "_site/" mais rien n'y fait: toujours pas les nouvelles pages et les nouveaux liens.

Ils donnent ces warnings:
```
WARN: Unresolved specs during Gem::Specification.reset:
      listen (< 3.1, ~> 3.0)
      rb-fsevent (>= 0.9.4, ~> 0.9)
      rb-inotify (>= 0.9.7, ~> 0.9)
WARN: Clearing out unresolved specs.
```

**Comment by ducdetronquito** [comment]
J'ai des problèmes aussi certaine dépendances...

Si je fais `bundle exec jekyll serve` j'ai plus d'erreurs par contre.

**Comment by sylsau** [comment]
Plus d'erreurs perso, mais osef je pense
