### ISSUE TITLE
Refaire toutes les footnotes

### ISSUE THREAD

**Issue by sylsau** [ResponSySS/responsyss.github.io#22]
Kramdown supporte les footnotes MD, et c'ay bowww. Avec des boutons pour revenir dans le texte, comme avec pandoc.
Ça me semblait étrange qu'ils les supportent pas.

![footballlol](https://user-images.githubusercontent.com/3996262/31676145-fba53e36-b366-11e7-9641-85776f9317bd.jpg)

je vais retravailler un peu le style

**Comment by ducdetronquito** [comment]
Je m'occupe de convertir les notes de bas de pages sur les textes que j'ai publié demain !

Par contre ouai, faut vraiment faire un style propre. La "flèche" pour revenir à la note de bas de page est beaucoup trop loin du texte, et le texte est beaucoup éloigné du numéro de note. (à mon humble avis)
