### ISSUE TITLE
Faire script pour générer les PDF/EPUB à partir des MD dans /textes/

### ISSUE THREAD

**Issue by sylsau** [ResponSySS/responsyss.github.io#24]
- [x] Mettre à jour en passant à `pdc_gen.sh` avec les bons paramètres
- [x] Générer des epubs
- [x] Convertir toutes les notes de bas de page en notes MD et minimiser au maximum l'usage des bloques HTML pour un résultat optimal
- [x] (Re)faire la template PDF
- [x] Faire une template EPUB
- [x] Réussir à générer 100% des textes en pdf

**Comment by ducdetronquito** [comment]
Est-ce que ce serait possible de générer aussi des fichiers PDF/EPUB pour les **posts** ?

Je viens de me rendre compte qu'il n'y en a pas pour l'instant, et ce serait vraiment cool en fait :)

**Comment by ducdetronquito** [comment]
Dans l'export PDF les images sont vachement zoomées, et des fois ça gène la compréhension (ex: sur les images d'articles de journaux dans *Misère du féminisme*

Est-ce qu'il y aurait moyen de virer ce zoom ? :O
