### ISSUE TITLE
Mettre liens vers les PDFs et les EPUBs

### ISSUE THREAD

**Issue by sylsau** [ResponSySS/responsyss.github.io#25]
Où ? [À DÉBATTRE]

**Comment by ducdetronquito** [comment]
Je pense qu'en haut du texte c'est plus pratique. Si le texte est long, ça me ferait chier d'avoir à scroller juste pour trouver le lien du pdf.

Je peux m'en occuper demain si ça te dit ?

**Comment by sylsau** [comment]
Oui clairement.
Vas-y fais un truc on verra.

**Comment by ducdetronquito** [comment]
Je viens d'ajouter un lien pour chaque texte/post pour lequel un pdf a été généré.
J'ai utilisé un petit icône en me disant qu'on aura la place d'ajouter un incône "epub" si nécessaire.

Qu'est ce que t'en penses ? :)

**Comment by sylsau** [comment]
L'icône est bien.
L'EPUB pourra être généré automatiquement par mon script, je m'en occupe.

**Comment by sylsau** [comment]
Faudrait que tu refasses une de ces icônes dont tu as le talent pour les EPUB.
Tout les EPUBs sont OK.

**Comment by ducdetronquito** [comment]
Mais quel Homme :3

**Comment by ducdetronquito** [comment]
Hop, c'est fait :3
