### ISSUE TITLE
Pas de redirection lors d'un changement d'article 

### ISSUE THREAD

**Issue by ducdetronquito** [ResponSySS/responsyss.github.io#28]
Lorsque l'on change d'article avec "article suivant" et "article précédent", la redirection n'est pas effectuée correctement, et pointe vers une page vierge.

Ex:
Passez de "Le fétichisme de la marchandise et sa conséquence [...]" et cliquer sur "article suivant"

**Comment by ducdetronquito** [comment]
En fait je viens de virer "article précédent" et "article suivant" à la fin des posts. C'est pas super utile et ça merde plein pot si ça implique une redirection.

**Comment by sylsau** [comment]
Bonne décision!
