### ISSUE TITLE
Update JQuery

### ISSUE THREAD

**Issue by ducdetronquito** [ResponSySS/responsyss.github.io#3]
Verify if our codebase really need to use JQuery. If it is the case, update from v1.11.2 to 3.2.1 and see if there is no regression.
If JQuery is not needed, remove this dependency.

**Comment by sylsau** [comment]
Donc il est needed ? :3

**Comment by ducdetronquito** [comment]
Malheureusement ouai... il est utilisé par la librairie bootstrap...

Un bon moyen de s'en débarasser serait de refaire le CSS entièrement à la main, (avec des flex-box pour se faciliter la vie) et par conséquent de virer bootstrap :3
