### ISSUE TITLE
Pandoc ne gère pas les images lors de la conversion markdown --> pdf

### ISSUE THREAD

**Issue by ducdetronquito** [ResponSySS/responsyss.github.io#30]
C'est un bug connu: https://github.com/sagemathinc/cocalc/issues/1965

Du coup je peux pas générer de PDF pour "Misère du féminisme" par exemple.

Et si j'utilise la définition d'image spécifique de pandoc, c'est jekyll qui ne sait plus générer la page HTML avec l'image...

Je sais que tu vas grincer des dents, mais y'aurait pas moyen d'utiliser une alternative à pandoc ? :P

**Comment by sylsau** [comment]
Solution: mettre tous les fichiers images nécessaires au texte dans le même dossier que les textes eux-mêmes, avec des chemins relatifs vers les images:
```
/textes/nom_prénom/texte.md
/textes/nom_prénom/img.jpg
[...]
```
```
![Quelle belle image](./img.jpg)

**Comment by sylsau** [comment]
MÀJ:
Problème décrit et traité dans: https://github.com/ResponSySS/responsyss.github.io/wiki/Générer-les-PDFs#chemins-dacc%C3%A8s-aux-images

**Comment by ducdetronquito** [comment]
Waow, ce mec qui hack le système, bien joué 👌 

Juste une question, est-ce qu'il faut ajouter les symlink à la main pour chaque image ou le générateur de pdf le fait tout seul ? (ou un script qu'on lancerait avec un git hook)

**Comment by sylsau** [comment]
Non il faut le faire, mais c'est simple:
```
cd textes/dominique_karamazov/
ln -s misere_du_feminisme/* .
```
