### ISSUE TITLE
Couleur invisible dans section Bibliothèque

### ISSUE THREAD

**Issue by sylsau** [ResponSySS/responsyss.github.io#37]
Vert aufhebung invisible sur iPhone et mobile !

![image](https://user-images.githubusercontent.com/3996262/35068890-ad26ff8c-fbd8-11e7-842f-b6522e4e04cf.png)

**Comment by sylsau** [comment]
L'enquête avance : en fait c'est WebKit qui foire :
(ici Chromium)
![webkitalakon](https://user-images.githubusercontent.com/3996262/35883621-1646c402-0b88-11e8-9f2c-b6544792389a.png)

**Comment by sylsau** [comment]
Problème résolu !!!!! Grâce À CE COMMIT INOUÏ HORS DU COMMUN APRÈS DES JOURS DE RECHERCHES !!! JE SUIS UNE LÉGENDE GUI, UNE LÉGENDE !!!!!! 
 →→→→→→→→→ ce831cb ←←←←←←←←←←

![webkitok](https://user-images.githubusercontent.com/3996262/35884239-5564ae40-0b8a-11e8-88f1-a61e6b9c7f88.png)

**Comment by ducdetronquito** [comment]
Mais putain mec. L'erreur indétectable.... G_G !
