### ISSUE TITLE
Phrase d'accroche sous le header principal

### ISSUE THREAD

**Issue by sylsau** [ResponSySS/responsyss.github.io#39]
Puissante mais concise, made in Andorin.

**Comment by sylsau** [comment]
To SVG or not to SVG, that is the question.

> Une image a été privilégié car ça serait con de stocker un fichier
police TTF qui sera utilisé une seule fois alors qu'on peut faire simplement et
moins lourd avec une simple image

What do you penser?

**Comment by ducdetronquito** [comment]
Il voulait une police spéciale juste pour ce texte ou pour tout le site ? Gnié pas compris :3

**Comment by sylsau** [comment]
Non juste pour la phrase d'accroche. Du coup c'est clairement mieux en format PNG ou SVG.
Mais du coup PNG ou SVG?
PNG: plus compatible.
SVG: plus high-tech.

Bon on va dire PNG quoi.

**Comment by ducdetronquito** [comment]
Ouai c'est nickel en PNG :)
