### ISSUE TITLE
Nouveaux icônes

### ISSUE THREAD

**Issue by sylsau** [ResponSySS/responsyss.github.io#43]
Le comité central du conserver-dépasser doit trancher : il faut changer les icônes, mais lesquelles mettre ?
Les anciens:
![emojis](https://user-images.githubusercontent.com/3996262/35417053-f23f9422-022b-11e8-8bc2-d6edd7ba9716.png)
Les nouveaux:
![palette d'icone made in Andorin](https://github.com/ResponSySS/responsyss.github.io/raw/master/build_aux/icones.png)
Ceux retenus so far:
![icones_choisis](https://user-images.githubusercontent.com/3996262/35417033-dbdd69a2-022b-11e8-8440-c6d2980dbb97.png)

Mais il va nous en refaire d'autre pour les epubs et pdf aussi donc on verra :-3

**Comment by ducdetronquito** [comment]
> Chi va piano, va sano e va lontano

Comme tu dis, on verra quand on aura le tout ;)

**Comment by sylsau** [comment]
En fait Andorin veut laisser tomber les icones et ouai les notres ils sont mieux en fait :-3

**Comment by ducdetronquito** [comment]
BOUM BITCH !

Zissiz Aweroll ! :D

**Comment by sylsau** [comment]
![bucket of water head walking on a car fight](https://user-images.githubusercontent.com/3996262/35876437-923bc348-0b72-11e8-8aff-741b8f306137.gif)
