### ISSUE TITLE
Re-design des post-cards d'accueil

### ISSUE THREAD

**Issue by sylsau** [ResponSySS/responsyss.github.io#44]
On a la pression putain !
(cf. photo du post)
https://www.facebook.com/AufhebungOfficiel/photos/a.1099127753446177.1073741828.1024455134246773/2287453324613608/

(on ignore la nouvelle phrase d'accroche, l'actuel est mieux)

**Comment by ducdetronquito** [comment]
[PRESSURE OVER 9000 !](https://www.youtube.com/watch?v=SiMHTK15Pik)

On est vraiment sensé virer les icônes ? Je trouve que c'est triste sans... :/

Pour ce qui est du menu, on fait quoi ? Quel lien pointe vers quelle partie du site ? ⭕️ 

Honnêtement je le trouve pas mal en l'état le site :)

**Comment by ducdetronquito** [comment]
D'ailleurs c'est où qu'il t'envoit toutes ces infos Guillaume ? :)

**Comment by sylsau** [comment]
Non non le menu on ignore hein.
Les icones ouai je suis d'accord, d'ailleurs j'ai remanié un peu l'alignement / les marges et c'est plus clean regarde.
Sur FB.
Non mais ça ira comme ça.

**Comment by ducdetronquito** [comment]
![](https://pbs.twimg.com/media/CWnb9j6WsAAXjrI.jpg)
