### ISSUE TITLE
SEO, preview Facebook et validation W3C

### ISSUE THREAD

**Issue by sylsau** [ResponSySS/responsyss.github.io#45]
- [x] optimisation pour les moteurs de recherche et l'indexation Google/FB
  - [x] utiliser `jekyll-seo-tag`
  - [x] utiliser `jekyll-sitemap` pour faire `sitemap.xml`
- [x] validation W3C

**Comment by sylsau** [comment]
Validation W3C: seul problème était le double `<title>` inséré dans le head.html : réglé dans  fc02f85e176d43247bd54d3d2c26fd204981f1a2

**Comment by ducdetronquito** [comment]
Ah c'était dont ça ! Bien joué :)

Est-ce que t'aurais moyen de virer le code mort ?
```
<!-- This is already generated by jekyll-seo-tags
+	  <title>{{ page.title }} | AUFHEBUNG</title>
+  -->
```

**Comment by sylsau** [comment]
Fallait le faire un, me demande pas lel.
C'est fait
