### ISSUE TITLE
Image OpenGraph spécifique à chaque post différente

### ISSUE THREAD

**Issue by sylsau** [ResponSySS/responsyss.github.io#48]
## Outils
Description du protocole : http://ogp.me/
Debugger OpenGraph : https://developers.facebook.com/tools/debug/og/object/

## Situation
Right now quand on partage Aufhebung sur FB/TW, l'image associé est le logo du site:
![default_img](https://user-images.githubusercontent.com/3996262/35826021-cf957f10-0ab7-11e8-9cfd-65180ceb139e.jpg)

Ce qu'il faudrait faire, c'est que l'image corresponde à chaque fois à l'article correspondant au lien partagé, comme ça:
![custom_img](https://user-images.githubusercontent.com/3996262/35826026-d2e271be-0ab7-11e8-9665-f7045b60c8f0.jpg)

**Comment by ducdetronquito** [comment]
T'as une idée de comment spécifié ça Oo ?

**Comment by ducdetronquito** [comment]
En tout cas je note qu'on partage des articles du site :D !

**Comment by sylsau** [comment]
C'est bon c'est fait.
![class](https://user-images.githubusercontent.com/3996262/35875195-d04ff07c-0b6e-11e8-9952-2646fd9b5f70.png)

**Comment by sylsau** [comment]
Amélioration: même quand les posts n'ont pas d'image (par exemple ceux de la bibliothèque), le 'thumbnail' est utilisé:
![class2](https://user-images.githubusercontent.com/3996262/35875633-3003ffb2-0b70-11e8-9a53-23a04d391e46.png)

**Comment by ducdetronquito** [comment]
Ce génie :3

**Comment by sylsau** [comment]
Mais faut que `thumbnail` soit spécifié dans le header YAML de la page, donc bien penser à le foutre à chaque nouveau texte, j'ai mis à jour le Wiki au cas où on ait un oubli : https://github.com/ResponSySS/responsyss.github.io/wiki/Publication-d'un-texte
