### ISSUE TITLE
Setup a Spirit instance

### ISSUE THREAD

**Issue by ducdetronquito** [ResponSySS/responsyss.github.io#5]

**Comment by ducdetronquito** [comment]
@ResponSySS 
Si tu veux essayer Spirit sur ta machine :)
https://github.com/ducdetronquito/aufhebung-spirit

**Comment by sylsau** [comment]
Faut obligatoirement que je fasse un compte?

**Comment by ducdetronquito** [comment]
Oui !
Mais là c'est un compte créé sur une base de données qui est stockée sur ton ordinateur :)

**Comment by sylsau** [comment]
Ah ok, je me disais.

**Comment by ducdetronquito** [comment]
Pour l'instant ce n'est plus d'actu, je ferme.
