### ISSUE TITLE
Spécifier les dépendances nécessaire pour la génération des PDB/EPUB.

### ISSUE THREAD

**Issue by ducdetronquito** [ResponSySS/responsyss.github.io#50]
Je n'arrive pas à générer les pdfs et les erreurs sont souvent incompréhensibles...

Est-ce que tu saurais lister tous les paquets nécessaires à installer pour faire fonctionner la génération des PDF/EPUB ? Comme ça je les installe une bonne fois pour toute :)

**Comment by sylsau** [comment]
Le set `pandoc` de base, et c'est tout normalement.
C'est quoi tes erreurs?
Tout devrait marcher en faisant (utliser `test[-pdf|-epub]` pour pas que ça écrase les PDF/EPUBs existants) :
```
cd mon_dossier_aufhebung.fr/ && make IN=textes/auteur/texte.md test
```

**Comment by ducdetronquito** [comment]
Je viens de retenter de générer les pds/epubs et j'ai toujours des polices manquantes:

```bash
mktextfm ecrm1200
```

Est-ce que tu pourrais rajouter une entrée *install* dans le Makefile qui ferait un joli apt-get install *full_stuff* ?

Comme ça on aura plus de doutes sur ce qui est nécessaire :D

**Comment by sylsau** [comment]
Alors apparemment, il faut aussi `latexextra`.
Donc normalement, c'est 1) le set de base + 2) `latexextra`.
Je sais pas comment les packages s'appellent sur Debian, mais je vais bientôt essayer sur mon PiPi.

`$ pacman -Q | grep "pandoc\|tex[^t ]" # comme 'dpkg --get-selections | grep...'`
```
haskell-pandoc-types 1.17.4.2-1
haskell-texmath 0.10.1.1-16
pandoc 2.1.3-11
pandoc-citeproc 0.13.0.1-52
pandoc-crossref 0.3.0.3-12
texinfo 6.5-1
texlive-bin 2017.44590-11
texlive-core 2017.46770-1
texlive-latexextra 2017.46778-1
```
Du coup en attendant j'ai ajouté une command Makefile, `deps` (bf1bddcc8675b55bb84e3b64d8f56df01a90d3d1).
`$ make deps`

`$ make OUT_TEST_PDF=/tmp/outfile.pdf test-pdf`

```bash
[...]
:: PDF: SUCCESS!
:: Output was made to '/tmp/outfile.pdf'
```

**Comment by sylsau** [comment]
MÀJ: j'ai effectivement réussi à `test-pdf` sur mon Raspbian avec tous les packets cités précédemment PLUS `texlive-lang-french`.
Par contre il faut bien avoir `pandoc` >= 2.0.0 et donc j'ai fait un système de check automatique quand on fait `make deps`.
