### ISSUE TITLE
Turbolinks

### ISSUE THREAD

**Issue by ducdetronquito** [ResponSySS/responsyss.github.io#51]
J'ai découvert une petite librairie JS nommée [Turbolinks](https://github.com/turbolinks/turbolinks) et qui permet d'optimiser la vitesse de navigation. (Je te laisse lire leur README :3)

Avantages:

- Vitesse de chargement des pages améliorée lors de la navigation.
- Si JS est desactivé, tout marche quand même.

Inconvenients:

- Rajoute 35Ko au chargement de la première page visitée.

Est-ce que tu peux me dire comment tu ressens la navigation sur le site si tu fais des aller-retour sur différentes pages ?

Si il s'avère que ce n'est pas pertinent je le vire :=)

**Comment by sylsau** [comment]
Ok, cool, faudrait comparer les temps de chargement avant et après avec Merdezilla, ça mettait combien de temps avant?
Ou alors si t'as pas noté faudrait annuler le commit des tubolinks, tester le temps de chargement, puis "désannuler" le commit, puis retester. Mais je sais pas comment on annule un commit ;_;
