### ISSUE TITLE
Les vidéos youtubes ne chargent pas.

### ISSUE THREAD

**Issue by ducdetronquito** [ResponSySS/responsyss.github.io#52]
Je n'arrive pas du tout à regarder les vidéos sur les pages où il y a un lecteur youtube intégré.

Est-ce que c'est pareil pour toi ?

Ex: http://aufhebung.fr/2017-10-l-heure-la-plus-sombre-87/

**Comment by sylsau** [comment]
Non, zéro problème pour moi, sur FF comme sur Chrome.
T'as essayé avec FF sans extension? Peut-être NoScript ou un truc du genre qui bloque les connexions extérieures?

**Comment by ducdetronquito** [comment]
![](http://image.noelshack.com/fichiers/2016/41/1476451468-1474553327-1474284978-1472388284-picsart-08-28-02-40-04.png)

Ah !

**Comment by sylsau** [comment]
T'as réessayé depuis ?

**Comment by ducdetronquito** [comment]
Effectivement, tout fonctionne :)
