### ISSUE TITLE
Certification SSL

### ISSUE THREAD

**Issue by sylsau** [ResponSySS/responsyss.github.io#55]
Donc j'ai réussi à faire certifier avec [SSL for Free](https://www.sslforfree.com/).
Seul problème : du coup maintenant je sais pas où foutre le certificat, la clé et tout.

... :+1: :duck: :goat: :cow2:  

En fait je crois que GitHub supporte pas l'encryption SSL depuis leur serveur, et qu'il faut passer par CloudFare pour que ça se fasse. Du coup je suis dég.
:sob: 

<https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b>
<https://www.goyllo.com/cloudflare-ssl-for-github-pages/>

**Comment by ducdetronquito** [comment]
Yep, Github ne supporte pas du tout le https pour les noms de domaines particuliers: je crois qu'ils ont une issue à ce propos depuis plus de 3 ans, mais sans nouvelles.

Du coup si on veut du HTTPS faudrait partir de Github ^^

**Comment by sylsau** [comment]
Mais du coup justement c'est possible en passant par CloudFare (cf les 2 liens de mon post)

**Comment by sylsau** [comment]
![https](https://user-images.githubusercontent.com/3996262/38166633-2b32caf0-3527-11e8-9b98-358c78e39439.png)
