### ISSUE TITLE
Remplacer Jekyll par Lektor

### ISSUE THREAD

**Issue by ducdetronquito** [ResponSySS/responsyss.github.io#63]
Qu'est ce que t'en dis :) ?
C'est un générateur de site statique comme Jekyll mais il permet d'éditer les pages via une interface web à la Wordpress: ça pourrait être pas mal pour que toute la bande contribue plus facilement :)

https://github.com/lektor/lektor

**Comment by sylsau** [comment]
Ça serait intéressant oui mais peut-être faudrait-il d'abord tenter des CMS qui existent déjà et qui supporte Jekyll:
* http://jekyllwriter.com/
* https://github.com/netlify/netlify-cms
* https://prose.io (CMS pour Github)
* https://www.siteleaf.com/ (version gratuite permet de poster)
* https://forestry.io/ (version gratuite permet de poster)

Jekyll Writer m'a l'air très prometteur ; je regarde ça.

**Comment by sylsau** [comment]
* **Jekyll Writer** : à l'air absolument juteux mais j'arrive pas à le faire marcher sur Linouze ;_;  
Démo : https://www.youtube.com/watch?v=t4HUrEs9d14

* **https://prose.io** : assez idéal, il faut juste naviguer vers "_posts" et ensuite on peut créer un post en 2-2 ; le seul hic c'est qu'il faut rentrer les métadonnées à la main<sup>1</sup>. Ça me semble loin d'être impossible à faire.  
Démo : https://drive.google.com/open?id=1kxLyRLWEiQ3Gme-0VsZ1MXyBqiThb4PK

***1*** : J'ai modifié `_config.yml` de manière à ce qu'ils aient juste à rentrer `title` et `subtitle` ; même `thumbnail` est optionnel (par défaut c'est le logo Aufhebung sur fond noir et d'ailleurs les images uploadées se foutent par défaut dans le dossier où on travaille donc faudra juste qu'on nettoie derrière s'ils savent pas où il faut uploader leurs images)

* **Netlify** : très propre, rapide à mettre en place et très pratique pour les contributeurs (il suffit de se connecter à `monsite.com/admin`). Il suffit juste de le configurer comme il faut (ce qui j'ai réussi à faire en 1/4 d'heure) et le bouzin marche du feu de dieu. Évidemment le site sera chez eux mais la formule gratuite de base va très bien pour les sites comme le nôtre. Custom domain et HTTPS simples à mettre en place.  
Démo : https://www.youtube.com/watch?v=9WWapoAChcM

**Comment by ducdetronquito** [comment]
J'ai juste jeter un oeil à toutes les alternatives que tu as proposé, donc mon avis est pas le plus pertinent, mais j'en retiens que:

- JekyllWriter semble non maintenu depuis plus d'un an, pour moi c'est un stop direct :/
- Netlify-cms semble vraiment être ouf :)

Ce qui me rassure avec Netlify c'est que c'est open source, qu'on peut potentiellement l'héberger nous même, et qu'on est pas à payer pour rajouter des nouveaux utilisateurs

J'essaye de creuser aussi leur documentation ce week end :)

Bien joué en tout cas !
